title: <p align="center"> Truong Bao Tran </p>  # your name (or website title) here
logo: "/assets/img/CV_Image.jpg?raw=true" 
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/bao-tran-truong08102001/">LinkedIn</a> |
  <a href="https://github.com/TruongBaoTran810">GitHub</a>
  </p>
  
  <p align="left">
  University of Economics and Law - Management Information Systems<br> 
  Data Analyst at Unilever Vietnam
  </p>
  
theme: jekyll-theme-minimal
