title: <p align="center"> Truong Bao Tran </p>  # your name (or website title) here
logo: "/assets/img/avartar.jpg?raw=true" 
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/bao-tran-truong08102001/">LinkedIn</a> |
  <a href="https://github.com/TruongBaoTran810">GitHub</a>
  </p>
  
  <p align="left">
  Management Information Systems - University of Economics and Law - VNUHCMC <br> 
  <h3>Objectives</h3> <br>
  <p> Short term: Improve and enhance skills in using data analysis tools such as Python, R, SQL, PowerBI and enhance experience in the field of Data as well as the ability to collect, synthesize, and process data from multiple sources, then analyze the data to identify trends, build predictive models. <br>
Long term: Develop and hone skills in using predictive models (Machine Learning) and continue to develop into a Data Scientist in the next 3 years. Supporting businesses to make quick, time-saving and highly accurate decisions.
  </p>
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
